# Generated by Django 4.2.7 on 2025-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomconfig',
            options={'verbose_name': '随机出题配置', 'verbose_name_plural': '随机出题配置'},
        ),
        migrations.RemoveField(
            model_name='randomconfig',
            name='easy_percent',
        ),
        migrations.RemoveField(
            model_name='randomconfig',
            name='hard_percent',
        ),
        migrations.RemoveField(
            model_name='randomconfig',
            name='medium_percent',
        ),
        migrations.AddField(
            model_name='randomconfig',
            name='difficulty',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难'), ('mixed', '混合')], default='mixed', max_length=10, verbose_name='难度级别'),
        ),
        migrations.AddField(
            model_name='randomconfig',
            name='question_types',
            field=models.JSONField(default=list, help_text='可选择多个题目类型', verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='randomconfig',
            name='categories',
            field=models.ManyToManyField(to='quiz_app.category', verbose_name='题目分类'),
        ),
        migrations.AlterField(
            model_name='randomconfig',
            name='total_questions',
            field=models.PositiveIntegerField(verbose_name='题目总数'),
        ),
    ]
